global:
  slack_api_url: 'INSERT SLACK URL HERE'

route:
  receiver: 'catchall'
  group_by: ['alertname']

  # When a new group of alerts is created by an incoming alert, wait at
  # least 'group_wait' to send the initial notification.
  # This way ensures that you get multiple alerts for the same group that start
  # firing shortly after another are batched together on the first
  # notification.
  group_wait: 30s

  # When the first notification was sent, wait 'group_interval' to send a batch
  # of new alerts that started firing for that group.
  group_interval: 5m

  # If an alert has successfully been sent, wait 'repeat_interval' to
  # resend them.
  repeat_interval: 5m

  routes:
  ## configure specific routes mapping alert <-> receiver

# Inhibition rules allow to mute a set of alerts given that another alert is
# firing.
# We use this to mute any warning-level notifications if the same alert is
# already critical.
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  # Apply inhibition if the alertname is the same.
  equal: ['alertname']

# Receivers indicate where the alert will go - pagerduty, slack, etc.
# For a full list of receivers: https://prometheus.io/docs/alerting/configuration/#<receiver>
receivers:
- name: 'catchall'
  slack_configs:
    - channel: '#k8s-alerts'
