version: '2'
services:
  prometheus:
    image: prom/prometheus:v1.5.2
    volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
        - ./rules:/etc/prometheus/rules
    command:
        - '-config.file=/etc/prometheus/prometheus.yml'
        - '-alertmanager.url=http://192.168.99.100:9093/'
    ports:
        - '9090:9090'
  grafana:
    image: grafana/grafana:3.0.0-beta7
    environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=pass
        - GF_DATABASE_TYPE=sqlite3
        - GF_DATABASE_HOST=192.168.99.100:3000
        - GF_DATABASE_PASSWORD=""
        - data=/var/lib/grafana
    depends_on:
        - prometheus
    ports:
        - "3000:3000"
  alertmanager:
    image: prom/alertmanager:v0.6.0
    volumes:
        - ./alertmanager.yml:/alertmanager.yml
    command:
        - '-config.file=/alertmanager.yml'
        - '-storage.path=/alertmanager'
        - '-web.external-url=http://localhost'
    ports:
      - "9093:9093"
  cAdvisor:
    image: google/cadvisor:v0.24.1
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
  server1:
    image: davejohnston/simple-webserver-container:latest
    ports:
      - "8888:80"
  server2:
    image: davejohnston/simple-webserver-container:latest
    ports:
      - "8880:80"
